version: '3.7'

services:
  nginx: 
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./html:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - beast
    networks:
      - backend

  beast:
    container_name: beast
    build:
      context: MessegeServer/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - backend

networks:
  backend:
    name: backend